
// Generated by Cadence Genus(TM) Synthesis Solution 22.14-s059_1
// Generated on: Sep 26 2024 16:49:48 CDT (Sep 26 2024 21:49:48 UTC)

// Verification Directory fv/uart_top 

module clock_divider(baud_rate, clk_in, clk_out, rst);
  input [3:0] baud_rate;
  input clk_in, rst;
  output clk_out;
  wire [3:0] baud_rate;
  wire clk_in, rst;
  wire clk_out;
  wire [31:0] clk_count;
  wire inc_add_102_27_n_0, inc_add_102_27_n_2, inc_add_102_27_n_4,
       inc_add_102_27_n_6, inc_add_102_27_n_9, inc_add_102_27_n_10,
       inc_add_102_27_n_12, inc_add_102_27_n_14;
  wire inc_add_102_27_n_16, inc_add_102_27_n_18, inc_add_102_27_n_21,
       inc_add_102_27_n_22, inc_add_102_27_n_25, inc_add_102_27_n_26,
       inc_add_102_27_n_28, inc_add_102_27_n_30;
  wire inc_add_102_27_n_32, inc_add_102_27_n_34, inc_add_102_27_n_36,
       inc_add_102_27_n_38, inc_add_102_27_n_40, inc_add_102_27_n_42,
       inc_add_102_27_n_44, inc_add_102_27_n_46;
  wire inc_add_102_27_n_48, inc_add_102_27_n_50, inc_add_102_27_n_52,
       inc_add_102_27_n_54, inc_add_102_27_n_56, inc_add_102_27_n_58,
       n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_48, n_49, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83;
  OR4X1 g956__2398(.A (n_49), .B (n_46), .C (n_45), .D (n_44), .Y
       (clk_out));
  OR4X1 g957__5107(.A (clk_count[14]), .B (clk_count[15]), .C (n_48),
       .D (n_43), .Y (n_44));
  NAND2BXL g958__6260(.AN (clk_count[13]), .B (n_42), .Y (n_43));
  OAI31X1 g959__4319(.A0 (clk_count[11]), .A1 (clk_count[10]), .A2
       (n_41), .B0 (clk_count[12]), .Y (n_42));
  NOR2BX1 g960__8428(.AN (clk_count[9]), .B (n_40), .Y (n_41));
  AOI21XL g961__5526(.A0 (clk_count[6]), .A1 (clk_count[7]), .B0
       (clk_count[8]), .Y (n_40));
  OR4X1 g962__6783(.A (clk_count[28]), .B (clk_count[29]), .C
       (clk_count[30]), .D (clk_count[31]), .Y (n_45));
  OR4X1 g963__3680(.A (clk_count[20]), .B (clk_count[21]), .C
       (clk_count[22]), .D (clk_count[23]), .Y (n_49));
  OR4X1 g964__1617(.A (clk_count[24]), .B (clk_count[25]), .C
       (clk_count[26]), .D (clk_count[27]), .Y (n_46));
  OR4X1 g965__2802(.A (clk_count[16]), .B (clk_count[17]), .C
       (clk_count[18]), .D (clk_count[19]), .Y (n_48));
  DFFHQX1 \clk_count_reg[31] (.CK (clk_in), .D (n_27), .Q
       (clk_count[31]));
  DFFHQX1 \clk_count_reg[19] (.CK (clk_in), .D (n_37), .Q
       (clk_count[19]));
  DFFHQX1 \clk_count_reg[20] (.CK (clk_in), .D (n_24), .Q
       (clk_count[20]));
  DFFHQX1 \clk_count_reg[21] (.CK (clk_in), .D (n_38), .Q
       (clk_count[21]));
  DFFHQX1 \clk_count_reg[22] (.CK (clk_in), .D (n_36), .Q
       (clk_count[22]));
  DFFHQX1 \clk_count_reg[23] (.CK (clk_in), .D (n_35), .Q
       (clk_count[23]));
  DFFHQX1 \clk_count_reg[24] (.CK (clk_in), .D (n_34), .Q
       (clk_count[24]));
  DFFHQX1 \clk_count_reg[25] (.CK (clk_in), .D (n_32), .Q
       (clk_count[25]));
  DFFHQX1 \clk_count_reg[26] (.CK (clk_in), .D (n_31), .Q
       (clk_count[26]));
  DFFHQX1 \clk_count_reg[27] (.CK (clk_in), .D (n_30), .Q
       (clk_count[27]));
  DFFHQX1 \clk_count_reg[28] (.CK (clk_in), .D (n_29), .Q
       (clk_count[28]));
  DFFHQX1 \clk_count_reg[29] (.CK (clk_in), .D (n_28), .Q
       (clk_count[29]));
  DFFHQX1 \clk_count_reg[30] (.CK (clk_in), .D (n_33), .Q
       (clk_count[30]));
  DFFHQX1 \clk_count_reg[18] (.CK (clk_in), .D (n_23), .Q
       (clk_count[18]));
  DFFHQX1 \clk_count_reg[2] (.CK (clk_in), .D (n_39), .Q
       (clk_count[2]));
  DFFHQX1 \clk_count_reg[1] (.CK (clk_in), .D (n_25), .Q
       (clk_count[1]));
  DFFHQX1 \clk_count_reg[16] (.CK (clk_in), .D (n_10), .Q
       (clk_count[16]));
  DFFHQX1 \clk_count_reg[17] (.CK (clk_in), .D (n_9), .Q
       (clk_count[17]));
  DFFHQX1 \clk_count_reg[6] (.CK (clk_in), .D (n_20), .Q
       (clk_count[6]));
  DFFHQX1 \clk_count_reg[7] (.CK (clk_in), .D (n_19), .Q
       (clk_count[7]));
  DFFHQX1 \clk_count_reg[8] (.CK (clk_in), .D (n_18), .Q
       (clk_count[8]));
  DFFHQX1 \clk_count_reg[9] (.CK (clk_in), .D (n_17), .Q
       (clk_count[9]));
  DFFHQX1 \clk_count_reg[10] (.CK (clk_in), .D (n_16), .Q
       (clk_count[10]));
  DFFHQX1 \clk_count_reg[4] (.CK (clk_in), .D (n_8), .Q (clk_count[4]));
  DFFHQX1 \clk_count_reg[12] (.CK (clk_in), .D (n_14), .Q
       (clk_count[12]));
  DFFHQX1 \clk_count_reg[13] (.CK (clk_in), .D (n_13), .Q
       (clk_count[13]));
  DFFHQX1 \clk_count_reg[14] (.CK (clk_in), .D (n_12), .Q
       (clk_count[14]));
  DFFHQX1 \clk_count_reg[15] (.CK (clk_in), .D (n_11), .Q
       (clk_count[15]));
  DFFHQX1 \clk_count_reg[11] (.CK (clk_in), .D (n_15), .Q
       (clk_count[11]));
  DFFHQX1 \clk_count_reg[5] (.CK (clk_in), .D (n_22), .Q
       (clk_count[5]));
  DFFHQX1 \clk_count_reg[3] (.CK (clk_in), .D (n_21), .Q
       (clk_count[3]));
  DFFHQX1 \clk_count_reg[0] (.CK (clk_in), .D (n_26), .Q
       (clk_count[0]));
  AND2XL g1203__1705(.A (n_82), .B (n_7), .Y (n_39));
  AND2XL g1204__5122(.A (n_7), .B (n_63), .Y (n_38));
  AND2XL g1205__8246(.A (n_7), .B (n_65), .Y (n_37));
  AND2XL g1206__7098(.A (n_7), .B (n_62), .Y (n_36));
  AND2XL g1207__6131(.A (n_7), .B (n_61), .Y (n_35));
  AND2XL g1208__1881(.A (n_7), .B (n_60), .Y (n_34));
  AND2XL g1209__5115(.A (n_7), .B (n_54), .Y (n_33));
  AND2XL g1210__7482(.A (n_7), .B (n_59), .Y (n_32));
  AND2XL g1211__4733(.A (n_7), .B (n_58), .Y (n_31));
  AND2XL g1212__6161(.A (n_7), .B (n_57), .Y (n_30));
  AND2XL g1213__9315(.A (n_7), .B (n_56), .Y (n_29));
  AND2XL g1214__9945(.A (n_7), .B (n_55), .Y (n_28));
  AND2XL g1215__2883(.A (n_7), .B (n_53), .Y (n_27));
  NOR2XL g1216__2346(.A (clk_count[0]), .B (n_6), .Y (n_26));
  AND2XL g1217__1666(.A (n_83), .B (n_7), .Y (n_25));
  AND2XL g1218__7410(.A (n_7), .B (n_64), .Y (n_24));
  NOR2BX1 g1219__6417(.AN (n_66), .B (n_6), .Y (n_23));
  NOR2BX1 g1220__5477(.AN (n_79), .B (n_6), .Y (n_22));
  NOR2BX1 g1221__2398(.AN (n_81), .B (n_6), .Y (n_21));
  NOR2BX1 g1222__5107(.AN (n_78), .B (n_6), .Y (n_20));
  NOR2BX1 g1223__6260(.AN (n_77), .B (n_6), .Y (n_19));
  NOR2BX1 g1224__4319(.AN (n_76), .B (n_6), .Y (n_18));
  NOR2BX1 g1225__8428(.AN (n_75), .B (n_6), .Y (n_17));
  NOR2BX1 g1226__5526(.AN (n_74), .B (n_6), .Y (n_16));
  NOR2BX1 g1227__6783(.AN (n_73), .B (n_6), .Y (n_15));
  NOR2BX1 g1228__3680(.AN (n_72), .B (n_6), .Y (n_14));
  NOR2BX1 g1229__1617(.AN (n_71), .B (n_6), .Y (n_13));
  NOR2BX1 g1230__2802(.AN (n_70), .B (n_6), .Y (n_12));
  NOR2BX1 g1231__1705(.AN (n_69), .B (n_6), .Y (n_11));
  NOR2BX1 g1232__5122(.AN (n_68), .B (n_6), .Y (n_10));
  NOR2BX1 g1233__8246(.AN (n_67), .B (n_6), .Y (n_9));
  NOR2BX1 g1234__7098(.AN (n_80), .B (n_6), .Y (n_8));
  INVX1 g1235(.A (n_7), .Y (n_6));
  AOI21X1 g1236__6131(.A0 (clk_count[0]), .A1 (n_5), .B0 (rst), .Y
       (n_7));
  NOR4BBX1 g1237__1881(.AN (clk_count[13]), .BN (n_4), .C
       (clk_count[15]), .D (clk_count[14]), .Y (n_5));
  NOR4BBX1 g1238__5115(.AN (clk_count[10]), .BN (n_3), .C
       (clk_count[12]), .D (clk_count[11]), .Y (n_4));
  NOR4BX1 g1239__7482(.AN (clk_count[8]), .B (clk_count[7]), .C
       (clk_count[9]), .D (n_2), .Y (n_3));
  NAND4BX1 g1240__4733(.AN (n_1), .B (clk_count[4]), .C (clk_count[5]),
       .D (clk_count[6]), .Y (n_2));
  NAND4XL g1241__6161(.A (clk_count[1]), .B (clk_count[2]), .C
       (clk_count[3]), .D (n_0), .Y (n_1));
  NOR4X1 g1242__9315(.A (n_46), .B (n_45), .C (n_48), .D (n_49), .Y
       (n_0));
  XNOR2X1 inc_add_102_27_g407__9945(.A (clk_count[31]), .B
       (inc_add_102_27_n_58), .Y (n_53));
  OA21X1 inc_add_102_27_g408__2883(.A0 (clk_count[30]), .A1
       (inc_add_102_27_n_56), .B0 (inc_add_102_27_n_58), .Y (n_54));
  NAND2X1 inc_add_102_27_g409__2346(.A (clk_count[30]), .B
       (inc_add_102_27_n_56), .Y (inc_add_102_27_n_58));
  XNOR2X1 inc_add_102_27_g410__1666(.A (clk_count[29]), .B
       (inc_add_102_27_n_54), .Y (n_55));
  NOR2BX1 inc_add_102_27_g411__7410(.AN (clk_count[29]), .B
       (inc_add_102_27_n_54), .Y (inc_add_102_27_n_56));
  OA21X1 inc_add_102_27_g412__6417(.A0 (clk_count[28]), .A1
       (inc_add_102_27_n_52), .B0 (inc_add_102_27_n_54), .Y (n_56));
  NAND2X1 inc_add_102_27_g413__5477(.A (clk_count[28]), .B
       (inc_add_102_27_n_52), .Y (inc_add_102_27_n_54));
  XNOR2X1 inc_add_102_27_g414__2398(.A (clk_count[27]), .B
       (inc_add_102_27_n_50), .Y (n_57));
  NOR2BX1 inc_add_102_27_g415__5107(.AN (clk_count[27]), .B
       (inc_add_102_27_n_50), .Y (inc_add_102_27_n_52));
  OA21X1 inc_add_102_27_g416__6260(.A0 (clk_count[26]), .A1
       (inc_add_102_27_n_48), .B0 (inc_add_102_27_n_50), .Y (n_58));
  NAND2X1 inc_add_102_27_g417__4319(.A (clk_count[26]), .B
       (inc_add_102_27_n_48), .Y (inc_add_102_27_n_50));
  AOI2BB1XL inc_add_102_27_g418__8428(.A0N (clk_count[25]), .A1N
       (inc_add_102_27_n_46), .B0 (inc_add_102_27_n_48), .Y (n_59));
  AND2XL inc_add_102_27_g419__5526(.A (clk_count[25]), .B
       (inc_add_102_27_n_46), .Y (inc_add_102_27_n_48));
  AOI2BB1XL inc_add_102_27_g420__6783(.A0N (clk_count[24]), .A1N
       (inc_add_102_27_n_44), .B0 (inc_add_102_27_n_46), .Y (n_60));
  AND2XL inc_add_102_27_g421__3680(.A (clk_count[24]), .B
       (inc_add_102_27_n_44), .Y (inc_add_102_27_n_46));
  XNOR2X1 inc_add_102_27_g422__1617(.A (clk_count[23]), .B
       (inc_add_102_27_n_42), .Y (n_61));
  NOR2BX1 inc_add_102_27_g423__2802(.AN (clk_count[23]), .B
       (inc_add_102_27_n_42), .Y (inc_add_102_27_n_44));
  OA21X1 inc_add_102_27_g424__1705(.A0 (clk_count[22]), .A1
       (inc_add_102_27_n_40), .B0 (inc_add_102_27_n_42), .Y (n_62));
  NAND2X1 inc_add_102_27_g425__5122(.A (clk_count[22]), .B
       (inc_add_102_27_n_40), .Y (inc_add_102_27_n_42));
  AOI2BB1XL inc_add_102_27_g426__8246(.A0N (clk_count[21]), .A1N
       (inc_add_102_27_n_38), .B0 (inc_add_102_27_n_40), .Y (n_63));
  AND2XL inc_add_102_27_g427__7098(.A (clk_count[21]), .B
       (inc_add_102_27_n_38), .Y (inc_add_102_27_n_40));
  XNOR2X1 inc_add_102_27_g428__6131(.A (clk_count[20]), .B
       (inc_add_102_27_n_36), .Y (n_64));
  NOR2BX1 inc_add_102_27_g429__1881(.AN (clk_count[20]), .B
       (inc_add_102_27_n_36), .Y (inc_add_102_27_n_38));
  OA21X1 inc_add_102_27_g430__5115(.A0 (clk_count[19]), .A1
       (inc_add_102_27_n_34), .B0 (inc_add_102_27_n_36), .Y (n_65));
  NAND2X1 inc_add_102_27_g431__7482(.A (clk_count[19]), .B
       (inc_add_102_27_n_34), .Y (inc_add_102_27_n_36));
  AOI2BB1XL inc_add_102_27_g432__4733(.A0N (clk_count[18]), .A1N
       (inc_add_102_27_n_32), .B0 (inc_add_102_27_n_34), .Y (n_66));
  AND2XL inc_add_102_27_g433__6161(.A (clk_count[18]), .B
       (inc_add_102_27_n_32), .Y (inc_add_102_27_n_34));
  XNOR2X1 inc_add_102_27_g434__9315(.A (clk_count[17]), .B
       (inc_add_102_27_n_30), .Y (n_67));
  NOR2BX1 inc_add_102_27_g435__9945(.AN (clk_count[17]), .B
       (inc_add_102_27_n_30), .Y (inc_add_102_27_n_32));
  XNOR2X1 inc_add_102_27_g436__2883(.A (clk_count[16]), .B
       (inc_add_102_27_n_28), .Y (n_68));
  NAND2BX1 inc_add_102_27_g437__2346(.AN (inc_add_102_27_n_28), .B
       (clk_count[16]), .Y (inc_add_102_27_n_30));
  OA21X1 inc_add_102_27_g438__1666(.A0 (clk_count[15]), .A1
       (inc_add_102_27_n_26), .B0 (inc_add_102_27_n_28), .Y (n_69));
  NAND2X1 inc_add_102_27_g439__7410(.A (clk_count[15]), .B
       (inc_add_102_27_n_26), .Y (inc_add_102_27_n_28));
  AOI2BB1XL inc_add_102_27_g440__6417(.A0N (clk_count[14]), .A1N
       (inc_add_102_27_n_25), .B0 (inc_add_102_27_n_26), .Y (n_70));
  AND2XL inc_add_102_27_g441__5477(.A (clk_count[14]), .B
       (inc_add_102_27_n_25), .Y (inc_add_102_27_n_26));
  ADDHX1 inc_add_102_27_g442__2398(.A (clk_count[13]), .B
       (inc_add_102_27_n_22), .CO (inc_add_102_27_n_25), .S (n_71));
  AOI2BB1XL inc_add_102_27_g443__5107(.A0N (clk_count[12]), .A1N
       (inc_add_102_27_n_21), .B0 (inc_add_102_27_n_22), .Y (n_72));
  AND2XL inc_add_102_27_g444__6260(.A (clk_count[12]), .B
       (inc_add_102_27_n_21), .Y (inc_add_102_27_n_22));
  ADDHX1 inc_add_102_27_g445__4319(.A (clk_count[11]), .B
       (inc_add_102_27_n_18), .CO (inc_add_102_27_n_21), .S (n_73));
  AOI2BB1XL inc_add_102_27_g446__8428(.A0N (clk_count[10]), .A1N
       (inc_add_102_27_n_16), .B0 (inc_add_102_27_n_18), .Y (n_74));
  AND2XL inc_add_102_27_g447__5526(.A (clk_count[10]), .B
       (inc_add_102_27_n_16), .Y (inc_add_102_27_n_18));
  AOI2BB1XL inc_add_102_27_g448__6783(.A0N (clk_count[9]), .A1N
       (inc_add_102_27_n_14), .B0 (inc_add_102_27_n_16), .Y (n_75));
  AND2XL inc_add_102_27_g449__3680(.A (clk_count[9]), .B
       (inc_add_102_27_n_14), .Y (inc_add_102_27_n_16));
  XNOR2X1 inc_add_102_27_g450__1617(.A (clk_count[8]), .B
       (inc_add_102_27_n_12), .Y (n_76));
  NOR2BX1 inc_add_102_27_g451__2802(.AN (clk_count[8]), .B
       (inc_add_102_27_n_12), .Y (inc_add_102_27_n_14));
  OA21X1 inc_add_102_27_g452__1705(.A0 (clk_count[7]), .A1
       (inc_add_102_27_n_10), .B0 (inc_add_102_27_n_12), .Y (n_77));
  NAND2X1 inc_add_102_27_g453__5122(.A (clk_count[7]), .B
       (inc_add_102_27_n_10), .Y (inc_add_102_27_n_12));
  AOI2BB1XL inc_add_102_27_g454__8246(.A0N (clk_count[6]), .A1N
       (inc_add_102_27_n_9), .B0 (inc_add_102_27_n_10), .Y (n_78));
  AND2XL inc_add_102_27_g455__7098(.A (clk_count[6]), .B
       (inc_add_102_27_n_9), .Y (inc_add_102_27_n_10));
  ADDHX1 inc_add_102_27_g456__6131(.A (clk_count[5]), .B
       (inc_add_102_27_n_6), .CO (inc_add_102_27_n_9), .S (n_79));
  AOI2BB1XL inc_add_102_27_g457__1881(.A0N (clk_count[4]), .A1N
       (inc_add_102_27_n_4), .B0 (inc_add_102_27_n_6), .Y (n_80));
  AND2XL inc_add_102_27_g458__5115(.A (clk_count[4]), .B
       (inc_add_102_27_n_4), .Y (inc_add_102_27_n_6));
  AOI2BB1XL inc_add_102_27_g459__7482(.A0N (clk_count[3]), .A1N
       (inc_add_102_27_n_2), .B0 (inc_add_102_27_n_4), .Y (n_81));
  AND2XL inc_add_102_27_g460__4733(.A (clk_count[3]), .B
       (inc_add_102_27_n_2), .Y (inc_add_102_27_n_4));
  AOI2BB1XL inc_add_102_27_g461__6161(.A0N (clk_count[2]), .A1N
       (inc_add_102_27_n_0), .B0 (inc_add_102_27_n_2), .Y (n_82));
  AND2XL inc_add_102_27_g462__9315(.A (clk_count[2]), .B
       (inc_add_102_27_n_0), .Y (inc_add_102_27_n_2));
  AOI2BB1XL inc_add_102_27_g463__9945(.A0N (clk_count[0]), .A1N
       (clk_count[1]), .B0 (inc_add_102_27_n_0), .Y (n_83));
  AND2XL inc_add_102_27_g464__2883(.A (clk_count[0]), .B
       (clk_count[1]), .Y (inc_add_102_27_n_0));
endmodule

module uart_rx(clk16x, clrn, rdn, d_out, r_ready, rxd, parity_error,
     frame_error, cnt16x, r_data, no_bits_rcvd, r_buffer, clk1x,
     sampling);
  input clk16x, clrn, rdn, rxd;
  input [3:0] cnt16x;
  output [7:0] d_out, r_data;
  output r_ready, parity_error, frame_error, clk1x, sampling;
  output [3:0] no_bits_rcvd;
  output [10:0] r_buffer;
  wire clk16x, clrn, rdn, rxd;
  wire [3:0] cnt16x;
  wire [7:0] d_out, r_data;
  wire r_ready, parity_error, frame_error, clk1x, sampling;
  wire [3:0] no_bits_rcvd;
  wire [10:0] r_buffer;
  wire [3:0] sampling_place;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_111, n_112, n_113, n_122, n_123;
  wire n_124, n_125, n_127, n_128, n_129, n_130, \r_data[0]_305 ,
       \r_data[1]_306 ;
  wire \r_data[2]_307 , \r_data[3]_308 , \r_data[4]_309 ,
       \r_data[5]_310 , \r_data[6]_311 , \r_data[7]_312 , rxd_new,
       rxd_old;
  assign r_buffer[0] = 1'b0;
  assign r_buffer[1] = 1'b0;
  assign r_buffer[2] = 1'b0;
  assign r_buffer[3] = 1'b0;
  assign r_buffer[4] = 1'b0;
  assign r_buffer[5] = 1'b0;
  assign r_buffer[6] = 1'b0;
  assign r_buffer[7] = 1'b0;
  assign r_buffer[8] = 1'b0;
  assign r_buffer[9] = 1'b0;
  assign r_buffer[10] = 1'b0;
  DFFSHQX1 rxd_old_reg(.SN (clrn), .CK (clk16x), .D (rxd_new), .Q
       (rxd_old));
  TBUFX20 g108__2346(.A (\r_data[0]_305 ), .OE (n_130), .Y (d_out[0]));
  TBUFX20 g101__1666(.A (n_129), .OE (n_130), .Y (d_out[7]));
  TBUFX20 g102__7410(.A (n_128), .OE (n_130), .Y (d_out[6]));
  DFFSHQX1 rxd_new_reg(.SN (clrn), .CK (clk16x), .D (rxd), .Q
       (rxd_new));
  TBUFX20 g103__6417(.A (n_124), .OE (n_130), .Y (d_out[5]));
  TBUFX20 g105__5477(.A (n_125), .OE (n_130), .Y (d_out[3]));
  TBUFX20 g104__2398(.A (n_127), .OE (n_130), .Y (d_out[4]));
  TBUFX20 g106__5107(.A (n_123), .OE (n_130), .Y (d_out[2]));
  TBUFX20 g107__6260(.A (n_122), .OE (n_130), .Y (d_out[1]));
  INVX3 g1688(.A (rdn), .Y (n_130));
  BUFX3 drc_bufs(.A (\r_data[7]_312 ), .Y (n_129));
  BUFX3 drc_bufs1689(.A (\r_data[6]_311 ), .Y (n_128));
  BUFX3 drc_bufs1690(.A (\r_data[4]_309 ), .Y (n_127));
  BUFX3 drc_bufs1692(.A (\r_data[3]_308 ), .Y (n_125));
  BUFX3 drc_bufs1693(.A (\r_data[5]_310 ), .Y (n_124));
  BUFX3 drc_bufs1694(.A (\r_data[2]_307 ), .Y (n_123));
  BUFX3 drc_bufs1695(.A (\r_data[1]_306 ), .Y (n_122));
  DFFRHQX1 clk1x_reg(.RN (clrn), .CK (clk16x), .D (n_95), .Q (clk1x));
  DFFRHQX1 frame_error_reg(.RN (n_36), .CK (clk16x), .D (n_73), .Q
       (n_111));
  DFFRHQX1 \no_bits_rcvd_reg[1] (.RN (n_98), .CK (clk1x), .D (n_44), .Q
       (n_100));
  SDFFRHQX1 \no_bits_rcvd_reg[2] (.RN (n_98), .CK (clk1x), .D (n_29),
       .SI (n_30), .SE (n_101), .Q (n_101));
  DFFRHQX1 parity_error_reg(.RN (n_36), .CK (clk16x), .D (n_97), .Q
       (n_112));
  DFFHQX1 \r_buffer_reg[0] (.CK (clk1x), .D (n_81), .Q (r_buffer[0]));
  DFFHQX1 \r_buffer_reg[1] (.CK (clk1x), .D (n_80), .Q (r_buffer[1]));
  DFFHQX1 \r_buffer_reg[2] (.CK (clk1x), .D (n_76), .Q (r_buffer[2]));
  DFFHQX1 \r_buffer_reg[3] (.CK (clk1x), .D (n_83), .Q (r_buffer[3]));
  DFFHQX1 \r_buffer_reg[4] (.CK (clk1x), .D (n_79), .Q (r_buffer[4]));
  DFFHQX1 \r_buffer_reg[5] (.CK (clk1x), .D (n_78), .Q (r_buffer[5]));
  DFFHQX1 \r_buffer_reg[6] (.CK (clk1x), .D (n_86), .Q (r_buffer[6]));
  DFFHQX1 \r_buffer_reg[7] (.CK (clk1x), .D (n_84), .Q (r_buffer[7]));
  DFFHQX1 \r_buffer_reg[8] (.CK (clk1x), .D (n_77), .Q (r_buffer[8]));
  DFFHQX1 \r_buffer_reg[9] (.CK (clk1x), .D (n_82), .Q (r_buffer[9]));
  DFFHQX1 \r_buffer_reg[10] (.CK (clk1x), .D (n_87), .Q (r_buffer[10]));
  SDFFRHQX1 \r_data_reg[0] (.RN (clrn), .CK (clk16x), .D (r_buffer[1]),
       .SI (n_3), .SE (n_53), .Q (n_3));
  SDFFRHQX1 \r_data_reg[1] (.RN (clrn), .CK (clk16x), .D (r_buffer[2]),
       .SI (n_5), .SE (n_53), .Q (n_5));
  SDFFRHQX1 \r_data_reg[2] (.RN (clrn), .CK (clk16x), .D (r_buffer[3]),
       .SI (n_6), .SE (n_53), .Q (n_6));
  SDFFRHQX1 \r_data_reg[3] (.RN (clrn), .CK (clk16x), .D (r_buffer[4]),
       .SI (n_7), .SE (n_53), .Q (n_7));
  SDFFRHQX1 \r_data_reg[4] (.RN (clrn), .CK (clk16x), .D (r_buffer[5]),
       .SI (n_8), .SE (n_53), .Q (n_8));
  SDFFRHQX1 \r_data_reg[5] (.RN (clrn), .CK (clk16x), .D (r_buffer[6]),
       .SI (n_9), .SE (n_53), .Q (n_9));
  SDFFRHQX1 \r_data_reg[6] (.RN (clrn), .CK (clk16x), .D (r_buffer[7]),
       .SI (n_10), .SE (n_53), .Q (n_10));
  SDFFRHQX1 \r_data_reg[7] (.RN (clrn), .CK (clk16x), .D (r_buffer[8]),
       .SI (n_4), .SE (n_53), .Q (n_4));
  DFFRHQX1 r_ready_reg(.RN (n_36), .CK (clk16x), .D (n_51), .Q (n_113));
  SDFFQX1 \sampling_place_reg[0] (.CK (clk16x), .D (cnt16x[0]), .SI
       (sampling_place[0]), .SE (n_54), .Q (sampling_place[0]));
  SDFFQX1 \sampling_place_reg[1] (.CK (clk16x), .D (cnt16x[1]), .SI
       (sampling_place[1]), .SE (n_54), .Q (sampling_place[1]));
  SDFFQX1 \sampling_place_reg[2] (.CK (clk16x), .D (cnt16x[2]), .SI
       (sampling_place[2]), .SE (n_54), .Q (sampling_place[2]));
  SDFFQX1 \sampling_place_reg[3] (.CK (clk16x), .D (n_27), .SI
       (sampling_place[3]), .SE (n_54), .Q (sampling_place[3]));
  SDFFRHQX1 sampling_reg(.RN (clrn), .CK (clk16x), .D (n_33), .SI
       (n_98), .SE (n_50), .Q (n_98));
  AO21X1 g2411__4319(.A0 (n_96), .A1 (n_46), .B0 (n_112), .Y (n_97));
  XNOR2X1 g2413__8428(.A (n_93), .B (n_59), .Y (n_96));
  OAI211X1 g2414__5526(.A0 (n_52), .A1 (n_74), .B0 (n_92), .C0 (n_94),
       .Y (n_95));
  OAI2BB1X1 g2415__6783(.A0N (n_49), .A1N (n_91), .B0 (clk1x), .Y
       (n_94));
  XNOR2X1 g2416__3680(.A (r_buffer[8]), .B (n_90), .Y (n_93));
  NAND3XL g2417__1617(.A (n_98), .B (clk1x), .C (n_89), .Y (n_92));
  OAI211X1 g2418__2802(.A0 (n_43), .A1 (n_85), .B0 (n_14), .C0 (n_98),
       .Y (n_91));
  XNOR2X1 g2419__1705(.A (r_buffer[2]), .B (n_88), .Y (n_90));
  OAI222XL g2433__5122(.A0 (n_14), .A1 (n_75), .B0 (n_34), .B1 (n_41),
       .C0 (n_20), .C1 (n_42), .Y (n_89));
  XNOR2X1 g2439__8246(.A (n_58), .B (r_buffer[7]), .Y (n_88));
  OAI21XL g2446__7098(.A0 (n_32), .A1 (n_57), .B0 (n_61), .Y (n_87));
  OAI21XL g2447__6131(.A0 (n_32), .A1 (n_56), .B0 (n_64), .Y (n_86));
  NOR2XL g2448__1881(.A (cnt16x[1]), .B (n_65), .Y (n_85));
  OAI21XL g2449__5115(.A0 (n_30), .A1 (n_56), .B0 (n_63), .Y (n_84));
  OAI21XL g2450__7482(.A0 (n_30), .A1 (n_13), .B0 (n_67), .Y (n_83));
  OAI21XL g2453__4733(.A0 (n_31), .A1 (n_57), .B0 (n_62), .Y (n_82));
  OAI21XL g2454__6161(.A0 (n_35), .A1 (n_13), .B0 (n_72), .Y (n_81));
  OAI21XL g2455__9315(.A0 (n_31), .A1 (n_13), .B0 (n_71), .Y (n_80));
  OAI21XL g2456__9945(.A0 (n_35), .A1 (n_56), .B0 (n_69), .Y (n_79));
  OAI21XL g2457__2883(.A0 (n_31), .A1 (n_56), .B0 (n_66), .Y (n_78));
  OAI21XL g2458__2346(.A0 (n_35), .A1 (n_57), .B0 (n_68), .Y (n_77));
  OAI21XL g2459__1666(.A0 (n_32), .A1 (n_13), .B0 (n_70), .Y (n_76));
  INVXL g2460(.A (n_74), .Y (n_75));
  OR2X1 g2461__7410(.A (n_111), .B (n_55), .Y (n_73));
  OAI21XL g2462__6417(.A0 (n_35), .A1 (n_40), .B0 (r_buffer[0]), .Y
       (n_72));
  OAI21XL g2463__5477(.A0 (n_31), .A1 (n_40), .B0 (r_buffer[1]), .Y
       (n_71));
  OAI21XL g2464__2398(.A0 (n_32), .A1 (n_40), .B0 (r_buffer[2]), .Y
       (n_70));
  OAI21XL g2465__5107(.A0 (n_35), .A1 (n_45), .B0 (r_buffer[4]), .Y
       (n_69));
  OAI21XL g2466__6260(.A0 (n_35), .A1 (n_47), .B0 (r_buffer[8]), .Y
       (n_68));
  NAND3XL g2467__4319(.A (n_43), .B (n_41), .C (n_42), .Y (n_74));
  OAI21XL g2470__8428(.A0 (n_30), .A1 (n_40), .B0 (r_buffer[3]), .Y
       (n_67));
  OAI21XL g2471__5526(.A0 (n_31), .A1 (n_45), .B0 (r_buffer[5]), .Y
       (n_66));
  AOI21XL g2472__6783(.A0 (n_22), .A1 (n_41), .B0 (n_42), .Y (n_65));
  OAI21XL g2473__3680(.A0 (n_32), .A1 (n_45), .B0 (r_buffer[6]), .Y
       (n_64));
  OAI21XL g2474__1617(.A0 (n_30), .A1 (n_45), .B0 (r_buffer[7]), .Y
       (n_63));
  OAI21XL g2475__2802(.A0 (n_31), .A1 (n_47), .B0 (r_buffer[9]), .Y
       (n_62));
  OAI21XL g2476__1705(.A0 (n_32), .A1 (n_47), .B0 (r_buffer[10]), .Y
       (n_61));
  OAI221X1 g2477__5122(.A0 (n_37), .A1 (n_30), .B0 (n_21), .B1 (n_29),
       .C0 (n_12), .Y (n_60));
  XNOR2X1 g2478__8246(.A (n_39), .B (r_buffer[5]), .Y (n_59));
  XNOR2X1 g2479__7098(.A (n_38), .B (r_buffer[4]), .Y (n_58));
  NOR2BX1 g2480__6131(.AN (n_46), .B (r_buffer[10]), .Y (n_55));
  NAND2BXL g2481__1881(.AN (n_47), .B (rxd), .Y (n_57));
  NAND2BXL g2482__5115(.AN (n_45), .B (rxd), .Y (n_56));
  AOI31X1 g2485__7482(.A0 (sampling_place[0]), .A1 (cnt16x[0]), .A2
       (n_98), .B0 (n_48), .Y (n_52));
  OR2X1 g2486__4733(.A (n_113), .B (n_46), .Y (n_51));
  NOR2XL g2487__6161(.A (n_33), .B (n_46), .Y (n_50));
  NAND3X1 g2488__9315(.A (n_18), .B (clrn), .C (n_33), .Y (n_54));
  NAND2X1 g2489__9945(.A (rdn), .B (n_46), .Y (n_53));
  INVXL g2490(.A (n_48), .Y (n_49));
  NAND2XL g2491__2883(.A (n_31), .B (n_32), .Y (n_44));
  NOR3XL g2492__2346(.A (sampling_place[0]), .B (cnt16x[0]), .C (n_18),
       .Y (n_48));
  OR2X1 g2493__1666(.A (n_18), .B (n_12), .Y (n_47));
  NOR2XL g2494__7410(.A (n_30), .B (n_12), .Y (n_46));
  OR2X1 g2495__6417(.A (n_18), .B (n_37), .Y (n_45));
  XNOR2X1 g2497__5477(.A (r_buffer[3]), .B (r_buffer[6]), .Y (n_39));
  XNOR2X1 g2498__2398(.A (sampling_place[1]), .B (cnt16x[1]), .Y
       (n_43));
  XNOR2X1 g2499__5107(.A (r_buffer[1]), .B (r_buffer[9]), .Y (n_38));
  XNOR2X1 g2500__6260(.A (sampling_place[2]), .B (cnt16x[2]), .Y
       (n_42));
  XNOR2X1 g2501__4319(.A (cnt16x[3]), .B (sampling_place[3]), .Y
       (n_41));
  NAND3BXL g2502__8428(.AN (n_101), .B (n_98), .C (n_21), .Y (n_40));
  NOR2XL g2503__5526(.A (cnt16x[2]), .B (cnt16x[1]), .Y (n_34));
  NAND2XL g2504__6783(.A (n_101), .B (n_21), .Y (n_37));
  AND2XL g2505__3680(.A (rdn), .B (clrn), .Y (n_36));
  OR2X1 g2506__1617(.A (n_100), .B (n_99), .Y (n_35));
  INVX1 g2508(.A (n_30), .Y (n_29));
  NOR2BX1 g2509__2802(.AN (rxd_old), .B (rxd_new), .Y (n_33));
  NAND2XL g2511__1705(.A (n_100), .B (n_19), .Y (n_32));
  OR2X1 g2512__5122(.A (n_100), .B (n_19), .Y (n_31));
  NAND2XL g2513__8246(.A (n_100), .B (n_99), .Y (n_30));
  INVXL g2516(.A (cnt16x[3]), .Y (n_27));
  CLKINVX6 g2519(.A (n_21), .Y (n_26));
  BUFX3 g2523(.A (n_101), .Y (n_25));
  CLKINVX6 g2526(.A (n_19), .Y (n_24));
  INVXL g2529(.A (n_98), .Y (n_18));
  BUFX3 g2532(.A (n_98), .Y (n_23));
  INVX1 drc_bufs2534(.A (cnt16x[1]), .Y (n_20));
  BUFX3 drc_bufs2539(.A (n_100), .Y (n_11));
  INVX1 drc_bufs2542(.A (cnt16x[2]), .Y (n_22));
  BUFX3 drc_bufs2579(.A (n_113), .Y (n_2));
  BUFX3 drc_bufs2583(.A (n_112), .Y (n_1));
  BUFX3 drc_bufs2587(.A (n_111), .Y (n_0));
  INVXL drc_bufs2590(.A (cnt16x[0]), .Y (n_14));
  CLKBUFX20 drc_bufs2592(.A (n_26), .Y (no_bits_rcvd[3]));
  CLKBUFX20 drc_bufs2593(.A (n_24), .Y (no_bits_rcvd[0]));
  CLKBUFX20 drc_bufs2594(.A (n_23), .Y (sampling));
  CLKBUFX20 drc_bufs2595(.A (n_25), .Y (no_bits_rcvd[2]));
  BUFX3 drc_bufs2599(.A (n_9), .Y (\r_data[5]_310 ));
  BUFX3 drc_bufs2600(.A (n_8), .Y (\r_data[4]_309 ));
  BUFX3 drc_bufs2601(.A (n_7), .Y (\r_data[3]_308 ));
  BUFX16 drc_bufs2602(.A (n_3), .Y (\r_data[0]_305 ));
  BUFX3 drc_bufs2603(.A (n_6), .Y (\r_data[2]_307 ));
  BUFX3 drc_bufs2604(.A (n_5), .Y (\r_data[1]_306 ));
  BUFX3 drc_bufs2605(.A (n_4), .Y (\r_data[7]_312 ));
  BUFX3 drc_bufs2606(.A (n_10), .Y (\r_data[6]_311 ));
  CLKBUFX20 drc_bufs2607(.A (n_11), .Y (no_bits_rcvd[1]));
  CLKBUFX20 drc_bufs2608(.A (n_0), .Y (frame_error));
  CLKBUFX20 drc_bufs2609(.A (n_1), .Y (parity_error));
  CLKBUFX20 drc_bufs2610(.A (n_2), .Y (r_ready));
  NAND2BX1 g2__7098(.AN (n_40), .B (rxd), .Y (n_13));
  NAND2BX1 g2649__6131(.AN (n_101), .B (n_102), .Y (n_12));
  CLKBUFX20 drc_bufs2655(.A (\r_data[0]_305 ), .Y (r_data[0]));
  CLKBUFX20 drc_bufs2663(.A (\r_data[7]_312 ), .Y (r_data[7]));
  CLKBUFX20 drc_bufs2671(.A (\r_data[6]_311 ), .Y (r_data[6]));
  CLKBUFX20 drc_bufs2679(.A (\r_data[5]_310 ), .Y (r_data[5]));
  CLKBUFX20 drc_bufs2687(.A (\r_data[4]_309 ), .Y (r_data[4]));
  CLKBUFX20 drc_bufs2695(.A (\r_data[3]_308 ), .Y (r_data[3]));
  CLKBUFX20 drc_bufs2703(.A (\r_data[2]_307 ), .Y (r_data[2]));
  CLKBUFX20 drc_bufs2711(.A (\r_data[1]_306 ), .Y (r_data[1]));
  DFFRX1 \no_bits_rcvd_reg[3] (.RN (n_98), .CK (clk1x), .D (n_60), .Q
       (n_102), .QN (n_21));
  DFFRX1 \no_bits_rcvd_reg[0] (.RN (n_98), .CK (clk1x), .D (n_19), .Q
       (n_99), .QN (n_19));
endmodule

module uart_tx(clk16x, clrn, wrn, d_in, t_empty, txd, cnt16x,
     no_bits_sent, t_buffer, clk1x, sending, t_data);
  input clk16x, clrn, wrn;
  input [7:0] d_in;
  input [3:0] cnt16x;
  output t_empty, txd, clk1x, sending;
  output [3:0] no_bits_sent;
  output [7:0] t_buffer, t_data;
  wire clk16x, clrn, wrn;
  wire [7:0] d_in;
  wire [3:0] cnt16x;
  wire t_empty, txd, clk1x, sending;
  wire [3:0] no_bits_sent;
  wire [7:0] t_buffer, t_data;
  wire clrn_buf, clrn_buf_clean, load_t_buffer, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, wrn_buf, wrn_buf_clean;
  TLATX1 clrn_buf_reg(.G (n_118), .D (clrn), .Q (clrn_buf), .QN (n_24));
  TLATX1 wrn_buf_reg(.G (n_119), .D (wrn), .Q (wrn_buf), .QN (n_25));
  NAND2BXL g565__1881(.AN (wrn_buf_clean), .B (wrn), .Y (n_119));
  NAND2BXL g566__5115(.AN (clrn_buf_clean), .B (clrn), .Y (n_118));
  DFFSHQX1 txd_reg(.SN (n_103), .CK (cnt16x[3]), .D (n_94), .Q (n_116));
  OAI211X1 g994__7482(.A0 (n_114), .A1 (n_82), .B0 (n_90), .C0 (n_93),
       .Y (n_94));
  OAI31X1 g995__4733(.A0 (n_113), .A1 (n_114), .A2 (n_92), .B0 (n_115),
       .Y (n_93));
  DFFHQX1 sending_reg(.CK (clk16x), .D (n_91), .Q (n_103));
  AOI22XL g997__6161(.A0 (n_112), .A1 (n_89), .B0 (n_23), .B1 (n_20),
       .Y (n_92));
  NOR2XL g998__9315(.A (n_24), .B (n_88), .Y (n_91));
  AOI22XL g999__9945(.A0 (n_114), .A1 (n_68), .B0 (n_110), .B1 (n_83),
       .Y (n_90));
  DFFRHQX1 \no_bits_sent_reg[3] (.RN (n_103), .CK (cnt16x[3]), .D
       (n_87), .Q (n_115));
  XNOR2X1 g1001__2883(.A (n_85), .B (n_84), .Y (n_89));
  XNOR2X1 g1002__2346(.A (n_103), .B (n_86), .Y (n_88));
  DFFHQX1 \t_buffer_reg[0] (.CK (clk16x), .D (n_81), .Q (n_104));
  DFFHQX1 \t_buffer_reg[1] (.CK (clk16x), .D (n_74), .Q (n_105));
  DFFHQX1 \t_buffer_reg[2] (.CK (clk16x), .D (n_79), .Q (n_106));
  DFFHQX1 \t_buffer_reg[3] (.CK (clk16x), .D (n_78), .Q (n_107));
  DFFHQX1 \t_buffer_reg[4] (.CK (clk16x), .D (n_77), .Q (n_108));
  DFFHQX1 \t_buffer_reg[5] (.CK (clk16x), .D (n_76), .Q (n_109));
  AO21X1 g1009__1666(.A0 (n_115), .A1 (n_50), .B0 (n_83), .Y (n_87));
  AOI21XL g1010__7410(.A0 (n_18), .A1 (n_65), .B0 (n_25), .Y (n_86));
  XNOR2X1 g1011__6417(.A (n_111), .B (n_71), .Y (n_85));
  XNOR2X1 g1012__5477(.A (n_105), .B (n_72), .Y (n_84));
  DFFHQX1 \t_buffer_reg[6] (.CK (clk16x), .D (n_75), .Q (n_110));
  DFFHQX1 \t_buffer_reg[7] (.CK (clk16x), .D (n_80), .Q (n_111));
  OR2X1 g1015__2398(.A (n_115), .B (n_69), .Y (n_82));
  NOR2XL g1016__5107(.A (n_24), .B (n_67), .Y (n_81));
  NOR2XL g1017__6260(.A (n_115), .B (n_50), .Y (n_83));
  DFFHQX1 load_t_buffer_reg(.CK (clk16x), .D (n_73), .Q
       (load_t_buffer));
  SDFFQX1 t_empty_reg(.CK (clk16x), .D (n_46), .SI (n_24), .SE (n_19),
       .Q (n_117));
  SDFFRHQX1 \no_bits_sent_reg[2] (.RN (n_103), .CK (cnt16x[3]), .D
       (n_29), .SI (n_114), .SE (n_33), .Q (n_114));
  NOR2XL g1021__4319(.A (n_24), .B (n_60), .Y (n_80));
  NOR2XL g1022__8428(.A (n_24), .B (n_66), .Y (n_79));
  NOR2XL g1023__5526(.A (n_24), .B (n_64), .Y (n_78));
  NOR2XL g1024__6783(.A (n_24), .B (n_63), .Y (n_77));
  NOR2XL g1025__3680(.A (n_24), .B (n_62), .Y (n_76));
  NOR2XL g1026__1617(.A (n_24), .B (n_61), .Y (n_75));
  NOR2XL g1027__2802(.A (n_24), .B (n_70), .Y (n_74));
  MXI2XL g1028__1705(.A (n_45), .B (n_24), .S0 (n_19), .Y (n_73));
  XNOR2X1 g1029__5122(.A (n_110), .B (n_36), .Y (n_72));
  XNOR2X1 g1030__8246(.A (n_104), .B (n_35), .Y (n_71));
  DFFHQX1 \t_data_reg[5] (.CK (clk16x), .D (n_56), .Q (n_100));
  DFFHQX1 \t_data_reg[6] (.CK (clk16x), .D (n_57), .Q (n_101));
  DFFHQX1 \t_data_reg[2] (.CK (clk16x), .D (n_52), .Q (n_97));
  DFFHQX1 \t_data_reg[0] (.CK (clk16x), .D (n_54), .Q (n_95));
  DFFHQX1 \t_data_reg[1] (.CK (clk16x), .D (n_55), .Q (n_96));
  DFFHQX1 \t_data_reg[7] (.CK (clk16x), .D (n_53), .Q (n_102));
  DFFHQX1 \t_data_reg[3] (.CK (clk16x), .D (n_58), .Q (n_98));
  DFFHQX1 \t_data_reg[4] (.CK (clk16x), .D (n_59), .Q (n_99));
  AOI22XL g1039__7098(.A0 (n_96), .A1 (n_49), .B0 (n_105), .B1 (n_48),
       .Y (n_70));
  AOI222X1 g1040__6131(.A0 (n_104), .A1 (n_32), .B0 (n_106), .B1
       (n_34), .C0 (n_105), .C1 (n_17), .Y (n_69));
  OAI31X1 g1041__1881(.A0 (n_31), .A1 (n_113), .A2 (n_112), .B0 (n_51),
       .Y (n_68));
  AOI22XL g1042__5115(.A0 (n_95), .A1 (n_49), .B0 (n_104), .B1 (n_48),
       .Y (n_67));
  AOI22XL g1043__7482(.A0 (n_97), .A1 (n_49), .B0 (n_106), .B1 (n_48),
       .Y (n_66));
  NAND4XL g1044__4733(.A (n_103), .B (n_115), .C (n_29), .D (n_34), .Y
       (n_65));
  AOI22XL g1045__6161(.A0 (n_98), .A1 (n_49), .B0 (n_107), .B1 (n_48),
       .Y (n_64));
  AOI22XL g1046__9315(.A0 (n_99), .A1 (n_49), .B0 (n_108), .B1 (n_48),
       .Y (n_63));
  AOI22XL g1047__9945(.A0 (n_100), .A1 (n_49), .B0 (n_109), .B1 (n_48),
       .Y (n_62));
  AOI22XL g1048__2883(.A0 (n_101), .A1 (n_49), .B0 (n_110), .B1 (n_48),
       .Y (n_61));
  AOI22XL g1049__2346(.A0 (n_102), .A1 (n_49), .B0 (n_111), .B1 (n_48),
       .Y (n_60));
  NOR2XL g1050__1666(.A (n_24), .B (n_47), .Y (n_59));
  NOR2XL g1051__7410(.A (n_24), .B (n_43), .Y (n_58));
  NOR2XL g1052__6417(.A (n_24), .B (n_41), .Y (n_57));
  NOR2XL g1053__5477(.A (n_24), .B (n_38), .Y (n_56));
  DFFRHQX1 \no_bits_sent_reg[1] (.RN (n_103), .CK (cnt16x[3]), .D
       (n_44), .Q (n_113));
  NOR2XL g1055__2398(.A (n_24), .B (n_42), .Y (n_55));
  NOR2XL g1056__5107(.A (n_24), .B (n_39), .Y (n_54));
  NOR2XL g1057__6260(.A (n_24), .B (n_40), .Y (n_53));
  NOR2XL g1058__4319(.A (n_24), .B (n_37), .Y (n_52));
  AOI22XL g1059__8428(.A0 (n_108), .A1 (n_32), .B0 (n_109), .B1 (n_17),
       .Y (n_51));
  INVX1 g1060(.A (n_49), .Y (n_48));
  AOI22XL g1061__5526(.A0 (n_25), .A1 (d_in[4]), .B0 (n_99), .B1
       (wrn_buf), .Y (n_47));
  NAND2BXL g1062__6783(.AN (n_117), .B (n_18), .Y (n_46));
  NAND2XL g1063__3680(.A (load_t_buffer), .B (n_18), .Y (n_45));
  DFFHQX1 wrn_buf_clean_reg(.CK (clk16x), .D (n_19), .Q
       (wrn_buf_clean));
  OR2X1 g1065__1617(.A (n_17), .B (n_32), .Y (n_44));
  AOI22XL g1066__2802(.A0 (n_25), .A1 (d_in[3]), .B0 (n_98), .B1
       (wrn_buf), .Y (n_43));
  NAND2XL g1067__1705(.A (n_114), .B (n_34), .Y (n_50));
  NOR2XL g1068__5122(.A (n_25), .B (n_18), .Y (n_49));
  AOI22XL g1069__8246(.A0 (n_25), .A1 (d_in[1]), .B0 (n_96), .B1
       (wrn_buf), .Y (n_42));
  AOI22XL g1070__7098(.A0 (n_25), .A1 (d_in[6]), .B0 (n_101), .B1
       (wrn_buf), .Y (n_41));
  AOI22XL g1071__6131(.A0 (n_25), .A1 (d_in[7]), .B0 (n_102), .B1
       (wrn_buf), .Y (n_40));
  AOI22XL g1072__1881(.A0 (n_25), .A1 (d_in[0]), .B0 (n_95), .B1
       (wrn_buf), .Y (n_39));
  AOI22XL g1073__5115(.A0 (n_25), .A1 (d_in[5]), .B0 (n_100), .B1
       (wrn_buf), .Y (n_38));
  AOI22XL g1074__7482(.A0 (n_25), .A1 (d_in[2]), .B0 (n_97), .B1
       (wrn_buf), .Y (n_37));
  XNOR2X1 g1075__4733(.A (n_107), .B (n_109), .Y (n_36));
  XNOR2X1 g1076__6161(.A (n_106), .B (n_108), .Y (n_35));
  INVX1 g1077(.A (n_33), .Y (n_34));
  DFFHQX1 clrn_buf_clean_reg(.CK (clk16x), .D (n_24), .Q
       (clrn_buf_clean));
  NAND2XL g1080__9315(.A (n_113), .B (n_112), .Y (n_33));
  NOR2XL g1083__9945(.A (n_113), .B (n_20), .Y (n_32));
  INVX1 g1086(.A (n_107), .Y (n_31));
  BUFX3 g1087(.A (n_107), .Y (n_30));
  INVX1 g1088(.A (n_114), .Y (n_29));
  BUFX3 g1090(.A (n_114), .Y (n_28));
  CLKINVX6 g1093(.A (n_20), .Y (n_27));
  BUFX3 g1096(.A (n_103), .Y (n_26));
  INVXL g1099(.A (n_111), .Y (n_23));
  BUFX3 g1100(.A (n_111), .Y (n_22));
  BUFX3 g1102(.A (n_113), .Y (n_21));
  BUFX3 drc_bufs1105(.A (n_115), .Y (n_16));
  BUFX3 drc_bufs1108(.A (n_109), .Y (n_15));
  BUFX3 drc_bufs1111(.A (n_105), .Y (n_14));
  BUFX3 drc_bufs1114(.A (n_104), .Y (n_13));
  BUFX3 drc_bufs1117(.A (n_108), .Y (n_12));
  BUFX3 drc_bufs1120(.A (n_106), .Y (n_11));
  BUFX3 drc_bufs1123(.A (n_110), .Y (n_10));
  BUFX3 drc_bufs1126(.A (n_96), .Y (n_9));
  BUFX3 drc_bufs1129(.A (n_95), .Y (n_8));
  BUFX3 drc_bufs1132(.A (n_102), .Y (n_7));
  BUFX3 drc_bufs1135(.A (n_101), .Y (n_6));
  BUFX3 drc_bufs1138(.A (n_100), .Y (n_5));
  BUFX3 drc_bufs1141(.A (n_99), .Y (n_4));
  BUFX3 drc_bufs1144(.A (n_98), .Y (n_3));
  BUFX3 drc_bufs1147(.A (n_97), .Y (n_2));
  BUFX3 drc_bufs1150(.A (n_117), .Y (n_1));
  BUFX3 drc_bufs(.A (n_116), .Y (n_0));
  CLKBUFX20 drc_bufs1151(.A (n_27), .Y (no_bits_sent[0]));
  CLKBUFX20 drc_bufs1152(.A (n_28), .Y (no_bits_sent[2]));
  CLKBUFX20 drc_bufs1153(.A (n_30), .Y (t_buffer[3]));
  CLKBUFX20 drc_bufs1154(.A (n_22), .Y (t_buffer[7]));
  CLKBUFX20 drc_bufs1155(.A (n_21), .Y (no_bits_sent[1]));
  CLKBUFX20 drc_bufs1156(.A (n_26), .Y (sending));
  CLKBUFX20 drc_bufs1157(.A (n_16), .Y (no_bits_sent[3]));
  CLKBUFX20 drc_bufs1158(.A (n_15), .Y (t_buffer[5]));
  CLKBUFX20 drc_bufs1159(.A (n_13), .Y (t_buffer[0]));
  CLKBUFX20 drc_bufs1160(.A (n_12), .Y (t_buffer[4]));
  CLKBUFX20 drc_bufs1161(.A (n_14), .Y (t_buffer[1]));
  CLKBUFX20 drc_bufs1162(.A (n_11), .Y (t_buffer[2]));
  CLKBUFX20 drc_bufs1163(.A (n_10), .Y (t_buffer[6]));
  CLKBUFX20 drc_bufs1164(.A (n_9), .Y (t_data[1]));
  CLKBUFX20 drc_bufs1165(.A (n_8), .Y (t_data[0]));
  CLKBUFX20 drc_bufs1166(.A (n_2), .Y (t_data[2]));
  CLKBUFX20 drc_bufs1167(.A (n_7), .Y (t_data[7]));
  CLKBUFX20 drc_bufs1168(.A (n_6), .Y (t_data[6]));
  CLKBUFX20 drc_bufs1169(.A (n_5), .Y (t_data[5]));
  CLKBUFX20 drc_bufs1170(.A (n_4), .Y (t_data[4]));
  CLKBUFX20 drc_bufs1171(.A (n_3), .Y (t_data[3]));
  CLKBUFX20 drc_bufs1172(.A (n_1), .Y (t_empty));
  CLKBUFX20 drc_bufs1173(.A (n_0), .Y (txd));
  NAND2XL g1220__2883(.A (wrn_buf), .B (clrn_buf), .Y (n_19));
  NAND2BX1 g2__2346(.AN (n_103), .B (load_t_buffer), .Y (n_18));
  NOR2BX1 g1221__1666(.AN (n_113), .B (n_112), .Y (n_17));
  DFFRX1 \no_bits_sent_reg[0] (.RN (n_103), .CK (cnt16x[3]), .D (n_20),
       .Q (n_112), .QN (n_20));
endmodule

module uart(clk16x, clrn, rdn, d_out, r_ready, rxd, parity_error,
     frame_error, wrn, d_in, t_empty, txd, cnt16x, no_bits_rcvd,
     r_buffer, r_clk1x, sampling, r_data, no_bits_sent, t_buffer,
     t_clk1x, sending, t_data);
  input clk16x, clrn, rdn, rxd, wrn;
  input [7:0] d_in;
  output [7:0] d_out, r_data, t_buffer, t_data;
  output r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  output [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  output [10:0] r_buffer;
  wire clk16x, clrn, rdn, rxd, wrn;
  wire [7:0] d_in;
  wire [7:0] d_out, r_data, t_buffer, t_data;
  wire r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  wire [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  wire [10:0] r_buffer;
  wire UNCONNECTED, UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z1, \cnt16x[0]_96 , \cnt16x[1]_97 ,
       \cnt16x[2]_98 , n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  uart_rx recver(clk16x, clrn, rdn, d_out, r_ready, rxd, parity_error,
       frame_error, {cnt16x[3], \cnt16x[2]_98 , \cnt16x[1]_97 ,
       \cnt16x[0]_96 }, r_data, no_bits_rcvd, r_buffer, r_clk1x,
       sampling);
  uart_tx sender(clk16x, clrn, wrn, d_in, t_empty, txd, {cnt16x[3],
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z},
       no_bits_sent, t_buffer, UNCONNECTED, sending, t_data);
  DFFRHQX1 \cnt16x_reg[3] (.RN (clrn), .CK (clk16x), .D (n_8), .Q
       (cnt16x[3]));
  XNOR2X1 g82__7410(.A (cnt16x[3]), .B (n_6), .Y (n_8));
  DFFRHQX1 \cnt16x_reg[2] (.RN (clrn), .CK (clk16x), .D (n_7), .Q
       (n_0));
  OA21X1 g84__6417(.A0 (n_0), .A1 (n_4), .B0 (n_6), .Y (n_7));
  DFFRHQX1 \cnt16x_reg[1] (.RN (clrn), .CK (clk16x), .D (n_5), .Q
       (n_1));
  NAND2XL g86__5477(.A (n_0), .B (n_4), .Y (n_6));
  AOI2BB1XL g87__2398(.A0N (n_1), .A1N (n_2), .B0 (n_4), .Y (n_5));
  AND2X1 g89__5107(.A (n_1), .B (n_2), .Y (n_4));
  BUFX6 drc_bufs(.A (n_2), .Y (\cnt16x[0]_96 ));
  BUFX6 drc_bufs98(.A (n_1), .Y (\cnt16x[1]_97 ));
  BUFX6 drc_bufs99(.A (n_0), .Y (\cnt16x[2]_98 ));
  CLKBUFX20 drc_bufs111(.A (\cnt16x[0]_96 ), .Y (cnt16x[0]));
  CLKBUFX20 drc_bufs119(.A (\cnt16x[1]_97 ), .Y (cnt16x[1]));
  CLKBUFX20 drc_bufs127(.A (\cnt16x[2]_98 ), .Y (cnt16x[2]));
  DFFRX1 \cnt16x_reg[0] (.RN (clrn), .CK (clk16x), .D (n_3), .Q (n_2),
       .QN (n_3));
endmodule

module uart_top(clk_230400, baud_rate_sel, clrn, rdn, d_out, r_ready,
     rxd, parity_error, frame_error, wrn, d_in, t_empty, txd, cnt16x,
     no_bits_rcvd, r_buffer, r_clk1x, sampling, r_data, no_bits_sent,
     t_buffer, t_clk1x, sending, t_data);
  input clk_230400, clrn, rdn, rxd, wrn;
  input [3:0] baud_rate_sel;
  input [7:0] d_in;
  output [7:0] d_out, r_data, t_buffer, t_data;
  output r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  output [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  output [10:0] r_buffer;
  wire clk_230400, clrn, rdn, rxd, wrn;
  wire [3:0] baud_rate_sel;
  wire [7:0] d_in;
  wire [7:0] d_out, r_data, t_buffer, t_data;
  wire r_ready, parity_error, frame_error, t_empty, txd, r_clk1x,
       sampling, t_clk1x, sending;
  wire [3:0] cnt16x, no_bits_rcvd, no_bits_sent;
  wire [10:0] r_buffer;
  wire UNCONNECTED0, UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5, clk16x;
  assign t_clk1x = cnt16x[3];
  clock_divider clk_divider(.baud_rate ({UNCONNECTED_HIER_Z5,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z2}),
       .clk_in (clk_230400), .clk_out (clk16x), .rst (clrn));
  uart uart(clk16x, clrn, rdn, d_out, r_ready, rxd, parity_error,
       frame_error, wrn, d_in, t_empty, txd, cnt16x, no_bits_rcvd,
       r_buffer, r_clk1x, sampling, r_data, no_bits_sent, t_buffer,
       UNCONNECTED0, sending, t_data);
endmodule


